server:
  port: 8081
jwt:
  secret: misecretomaximoquedebeserlargoosinoestopeta
  header: Authorization
  prefix: Bearer
  expirationMs: 300000
  cookieName: jwt-cookie
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #hibernate:
    #  ddl-auto: update

